name: Keep Render App Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s https://qa-bot-4sdr.onrender.com/auth > /dev/null
